# Application configuration
app:
  name: "Our digital islamic world backend"
  description: "Description of your application"

# OpenSearch connection details
opensearch:
  host: "opensearch"
  port: "9200"
  username: "admin"
  password: "yourStrongPassword123!"

# Web server configuration
server:
  host: "localhost"
  port: "8080"

# Logging configuration
logging:
  loglevel: "info"
